"""followers

Revision ID: 53003ca09174
Revises: a7052c3ebaf3
Create Date: 2018-01-07 15:45:03.806681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53003ca09174'
down_revision = 'a7052c3ebaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
